### ISSUE TITLE
[Servicios & Migraciones] Crear CRUD de clases

### ISSUE THREAD

**Issue by JoseScap** [JoseScap/GymManagementApi#27]
# [Servicios & Migraciones] Crear CRUD de clases

## Descripción

Esta tarea consiste en la creación de un CRUD para las clases impartidas en gimnasios. Se deberán realizar las siguientes actividades en orden:

1. **Detallar la entidad:** Definir la estructura de la entidad en TypeScript y MySQL.
2. **Generar la migración:** Crear una migración para la base de datos que refleje la entidad definida.
3. **Realizar el controlador y servicios:** Implementar los controladores y servicios necesarios para manejar las operaciones CRUD.

## Detalle de la Entidad

- **id:** GUID/UUID
  - TypeScript: `string`
  - MySQL: `varchar(36)`
  
- **className:** Nombre de la clase
  - TypeScript: `string`
  - MySQL: `varchar(50)`
  
- **professor:** Nombre del profesor
  - TypeScript: `string`
  - MySQL: `varchar(50)`

- **total:** Recaudacion total de la clase
  - TypeScript: `number`
  - MySQL: `decimal(10,2)`  

- **date:** Fecha de la clase
  - TypeScript: `Date`
  - MySQL: `timestamp`
  
- **isCanceled:** Atributo de soft delete
  - TypeScript: `boolean`
  - MySQL: `boolean`
  
- **createdAt:** Timestamp de creación
  - MySQL: `timestamp`
  
- **updatedAt:** Timestamp de actualización
  - MySQL: `timestamp`

## Servicios y Controladores

Se deberán implementar los siguientes servicios y controladores:

- **findOne:** Obtener una clase por su ID.
- **findPaginated:** Obtener una lista paginada de clases.
- **createOne:** Crear una nueva clase.
- **updateOne:** Actualizar una clase existente.
- **removeOne:** Eliminar una clase (soft delete).
- **restoreOne:** Restaurar una clase eliminada.

**Comment by FranprzDev** [comment]
Ya cree todos, y creo que los cree bien, también agregué los DTOS; los probé en postman y funcionan.
